name: Teste Pipeline

on:
  push:
    branches:
      - main
      - dev
      - teste

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 📂 Listar arquivos
        run: ls -la

      - name: 🧪 Teste simples
        run: echo "Pipeline funcionando!"